input_basedir: "."

input:
  - name: "accommodation"
  - name: "administration"
  - name: "amenity"
  - name: "barrier"
  - name: "eat-drink"
  - name: "emergency"
  - name: "energy"
  - name: "health"
  - name: "money"
  - name: "nature"
  - name: "outdoor"
  - name: "religious"
  - name: "shop"
  - name: "sports"
  - name: "tourism"
  - name: "transport"

output_basedir: "export-umap-light"
# WARNING: deletes all files within output directory if it exists
empty_output: true
format: "png"
#retina: true
dpi: 180
subdirs: false

global_style:
  padding: 1
  fill: "#ffffff"
